stages:
- name: deploy-grafana-dash
  steps:
  - applyYamlConfig:
      path: ./grafana-dash.yaml
timeout: 60
notification:
  recipients:
  - recipient: team-infra
    notifier: c-75kcc:n-wpjss
  condition:
  - Success
  - Changed
  - Failed
