---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gfn-dash-pvc
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: grafana
  namespace: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
          runAsUser: 472
          fsGroup: 472      
      containers:
        - image: grafana/grafana
          imagePullPolicy: Always
          name: grafana
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 2Gi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-volume-1
      volumes:
        - name: grafana-volume-1
          persistentVolumeClaim:
            claimName: gfn-dash-pvc


---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: grafana
  labels:
    service: grafana
  name: grafana
spec:
  type: "ClusterIP"
  ports:
  - port: 3000
    targetPort: http-grafana
    protocol: TCP
  selector:
    service: grafana


---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: grafana
  name: grafana
  annotations:
    allow.http: "false"
spec:
  rules:
  - host: grafana.rancher.k8smaster.club
    http:
      paths:
        - path: /
          backend:
            serviceName: grafana
            servicePort: http-grafana
